# Generated by Django 5.0.14 on 2025-08-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_remove_booking_booking_time_alter_booking_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reservation_slot',
            field=models.CharField(default='TBD', max_length=20),
        ),
    ]
